name: ipython-notebook
dependencies:
  - notebook
  - ipywidgets
  - requests
  - cycler
  - matplotlib
  - python-dateutil
  - pyparsing
  - pytz
  - git
  - gitpython
  - pip:
    - git+git://github.com/ipython-contrib/jupyter_contrib_nbextensions.git
