name: ipython-notebook
dependencies:
  - notebook
  - ipywidgets
  - requests
  - git
  - gitpython
  - theano
  - keras
  - pip:
    - git+git://github.com/ipython-contrib/jupyter_contrib_nbextensions.git
